### PR TITLE
Add support for specifying Kafka key

### PR DESCRIPTION
**Pull request by pksu**
Introduce a new command line switch to enable string based Kafka key
(that is disabled by default).

### CODE REVIEW

**Comment by lspgn** [comment]
We can add this, I am just wondering your use case: do you need to send flows to a specific partition?
I would imagine keying via specific attributes (eg: router address).

**Comment by simPod** [comment]
Personally, I'd use this to partition messages by device (so eg. use sflow listening port).

**Comment by simPod** [comment]
Just stumbled upon the use case where I need to identify port through `inif/outif + device`. I could extract device identifier from key if it was there. Currently, there's no other way to identifiy device when consuming from kafka I think.

**Comment by simPod** [comment]
That would IMO solve every issue I can come up with right now 👍

**Comment by lspgn** [comment]
Overdue but added the feature in GoFlow v3:
https://github.com/cloudflare/goflow/blob/master/transport/kafka.go#L49

**Pull request closed without merging**
