### PR TITLE
Rename SrcIf to InIf and DstIf to OutIf

### LINKED ISSUE #28: DstIf/SrcIf vs InIf/OutIf naming
Hi, what is the reason for naming fields as DstIf and SrcIf? So far I have seen InIf and OutIf naming for the same thing. Thanks!

### PR DESCRIPTION
**Pull request by simPod**
Closes #28

### CODE REVIEW

**Comment by lspgn** [comment]
Looks like Travis was having issues fetching libraries.
Was the proto regenerated using `protoc`?

Thank you

**Comment by simPod** [comment]
Just regenerated through `protoc`

**Comment by lspgn** [comment]
did you run `PROTOCPATH=$HOME/go/bin/ make proto`? Getting slightly different protobuf generated file.

**Comment by simPod** [comment]
@lspgn I run this now `PROTOCPATH=/usr/local/bin make proto` There were some changes, check now 🤔

**Pull request merged**
