### PR TITLE
Add option for so_reuserport for NetFlow and sFlow

### PR DESCRIPTION
**Pull request by kanocz**
In some cases (for better performance) it's good to have more instances of goflow running on same UDP ports, but locked to some cpu cores. This patch enables optional use of so_reuseport for UDP listen giving this possibility.

### CODE REVIEW

**Comment by lspgn** [comment]
Hello,
Thank you for this PR.
Regarding multithreading the decoding CPU, you can set a number of workers that the main thread will dispatch for decoding. This handles NetFlow/IPFIX templates.
I am not entirely familiar with SO_REUSEPORT and the multi-platform support. Is it load-balanced/random/... as unless it is hashed, we'd loose the templating functionality.
I do not mind adding this feature, but I'd rather make sure this works on other platforms and would support NetFlow v9/IPFIX if that is not replaceable by setting a number of workers for processing.

**Comment by kanocz** [comment]
@lspgn it works on unix/bsd and also on windows, but system implementation is different, so no guaranty for same hashing in multi-platform context. But as for me it's good optional feature for some use cases
and yes for example on Linux when you use more instances which are locked to different cpu cores together with network card queues it can hash much-much better performance (no interconnection between threads, no numa-node issues, memory synchronization and so on)

**Comment by lspgn** [comment]
I see: it makes sense.
Have you used it with sFlow only? Do you know anyone else who would be benefitting from this functionality or had any feedbacks?
I will take a look at the new library and merge.
Would you mind taking a look at the v3 of GoFlow? It slightly changes the part with the socket binding.

**Comment by kanocz** [comment]
Yes, used it only for sFlow now... and some friends from CDN77 also used it in such way :)
Hm... looks like v3 changes many things... if you want I'll prepare same patch for v3 also, but need little bit more time to test if this will get same performance boost and make sense for v3

**Comment by lspgn** [comment]
Good to know :) 
I will release an update to v2 (among with a few others PRs).
Before releasing v3, I will add yours as well: the the gain of performance should still be present. It's mainly a change in structure (and schema): just so you're aware if you're not using vanilla GoFlow and have flow processors in the pipeline.

Thank you!

**Comment by lspgn** [comment]
Just made a commit in v3, reusing your code. I need to update the structures in order to pass the reuse parameter. Need to test it now:
https://github.com/cloudflare/goflow/commit/77528269ea9510b1b91f20740d1cf6738465d54d

**Pull request merged**
